---
- name: installer
  hosts: all
  tasks:
    - name: Install packages
      apt:
        name:
          - nginx
          - openssl
          - vim
          - zsh
          - python3-pip
          - git
          - curl
          - neofetch
          - openssh-server
          - docker
          - docker.io
          - docker-compose
        state: present
        update_cache: true

    - name: change moduser
      ansible.builtin.user:
        name: '{{ ansible_user }}'
        groups: docker,sudo
        append: yes
        shell: /bin/zsh

    - name: pull my dot files
      git:
        repo: https://github.com/stefanTrawicki/dot-files.git
        dest: /home/{{ ansible_user }}/dot-files
        clone: yes
        update: yes

    - name: run the dot file linker
      command: sh /home/{{ ansible_user }}/dot-files/link.sh
      ignore_errors: yes

  roles:
    - role: artis3n.tailscale
      vars:
        tailscale_up_skip: true
    
  become: yes